- mittab/apps/tab/forms.py
Will look at Kevin's PR later, this is the bare minimum change to get deployed for APDA summer
> Simple change to speaks bounds

- requirements.txt
It's used by the compute_stats command
> Add numpy dependency to requirements.txt

- bin/SpeaksDist.py
I've been manually making the raw speaks data a list of strings, not sure if there's an easier way to do that to align with the data output from mit-tab.
> Add speaks distribution script

- mittab/apps/tab/pairing_views.py
- mittab/apps/tab/templates/pairing_control.html
- mittab/static/javascript/pairings.js
- mittab/urls.py
I've never seen this used, but I have seen it accidentally change pairings
> Remove drag/drop team swap

- mittab/apps/tab/debater_views.py
- mittab/apps/tab/forms.py
- mittab/apps/tab/templates/thanks.html
- mittab/apps/tab/views.py
- mittab/libs/data_import/import_teams.py
Replace TODO comments with issues
> Remove TODOs

- mittab/apps/tab/pairing_views.py
- mittab/apps/tab/templates/pairing_control.html
- mittab/static/javascript/pairings.js
- mittab/urls.py
> Revert "Remove drag/drop team swap"

- mittab/settings.py
- requirements.txt
> Django 1.8

- mittab/apps/tab/management/commands/simulate_rounds.py
- mittab/apps/tab/models.py
- mittab/libs/tab_logic.py
Teams with a lenient_late should be paired into the middle of the bracket when they have no speaks
> Lenient late fix

- mittab/apps/tab/forms.py
- mittab/apps/tab/pairing_views.py
- mittab/apps/tab/templates/round_pairings.html
- Show # of teams in the pairing view
- Sort teams/debaters in drop-downs alphabetically
> Small UX Improvements

- mittab/apps/tab/judge_views.py
- mittab/apps/tab/models.py
- mittab/apps/tab/pairing_views.py
- mittab/apps/tab/templates/batch_checkin.html
- mittab/apps/tab/templates/navigation.html
- mittab/static/css/stylesheet.css
- mittab/static/javascript/pairings.js
- mittab/static/javascript/tab.js
- mittab/urls.py
> Batch judge check-in

- mittab/apps/tab/middleware.py
- mittab/apps/tab/pairing_views.py
- mittab/apps/tab/templates/missing_ballots.html
- mittab/apps/tab/templates/registration/login.html
- mittab/urls.py
adding a feature mid-tournament yolo
> Missing ballots page

- mittab/apps/tab/pairing_views.py
So people dont think there is any meaning to it
> Alphabetize judges in missing ballots

- .travis.yml
- requirements.txt
The code coverage on most things sucks. But we should at least shoot for 100% on the tab_logic library
> Add coveralls for code coverage

- mittab/apps/tab/debater_views.py
- mittab/apps/tab/team_views.py
- mittab/libs/tab_logic/__init__.py
- mittab/libs/tab_logic/rankings.py
- mittab/libs/tab_logic/stats.py
- mittab/libs/tests/test_tab_logic.py
This PR cleans up the tab logic library into 1 main library with some sub-modules. Goals are to separate:
- stats calculations
- rankings
- pairing
And also to improve performance
> Tab logic cleanup

- .circleci/config.yml
- mittab/static/javascript/forms.js
- requirements.txt
Looks like no real changes need to be made for this one
> Django 1.11

- mittab/apps/tab/debater_views.py
- mittab/apps/tab/judge_views.py
- mittab/apps/tab/team_views.py
- mittab/apps/tab/views.py
- mittab/libs/tests/web/test_setting_up_a_tournament.py
- mittab/urls.py
Miscellaneous deleting of unused code and testing of used code
> Simple code coverage increases

- assets/css/app.scss
- mittab/apps/tab/templates/base_new.html
- mittab/apps/tab/templates/navigation_new.html
- mittab/apps/tab/templates/registration/logged_out.html
- mittab/apps/tab/templates/registration/login.html
- mittab/apps/tab/views.py
- mittab/settings.py
- mittab/urls.py
> Update log-in/out page

- assets/css/app.scss
- assets/js/index.js
- mittab/apps/tab/templates/batch_checkin.html
> New Batch Check-In Design

- assets/js/index.js
- assets/js/pairing.js
- mittab/apps/tab/debater_views.py
- mittab/apps/tab/team_views.py
- mittab/apps/tab/templates/batch_checkin.html
- mittab/apps/tab/templates/rank_debaters.html
- mittab/apps/tab/templates/rank_debaters_component.html
- mittab/apps/tab/templates/rank_teams.html
- mittab/apps/tab/templates/rank_teams_component.html
kinda ugly looking but whatever
> Switch ranking views to new design

- mittab/libs/tests/assertion.py
- mittab/libs/tests/data/generate_data.py
- mittab/libs/tests/data/load_data.py
- mittab/libs/tests/helpers.py
- mittab/libs/tests/tab_logic/test_pairing.py
- mittab/libs/tests/tab_logic/test_ranking_logic.py
- mittab/libs/tests/test_case.py
- mittab/libs/tests/web/test_pairing_a_round.py
- mittab/libs/tests/web/test_setting_up_a_tournament.py
> Python reformat mittab/libs/tests/*

- mittab/apps/tab/debater_views.py
- mittab/apps/tab/management/commands/export_stats.py
- mittab/apps/tab/models.py
- mittab/apps/tab/team_views.py
- mittab/apps/tab/templates/tab/rank_debaters.html
- mittab/apps/tab/templates/tab/rank_debaters_component.html
- mittab/apps/tab/templates/tab/rank_teams.html
- mittab/apps/tab/templates/tab/rank_teams_component.html
- mittab/libs/tab_logic/rankings.py
- mittab/libs/tab_logic/stats.py
> Display tiebreakers on the rankings page

- mittab/apps/tab/fixtures/testing_db.json
- mittab/apps/tab/models.py
Resolves #104 — had to also remove a duplicate in the fixture.
No one front end wise will realize a change, there will just no longer be duplicate scratches in the db.
> Added unique_together for scratches

- assets/js/pairingDisplay.js
- assets/js/publicDisplay.js
- assets/js/scroller.js
now that lint passes on python, should run it on JS stuff
> Run prettier on files failing lint

- mittab/templates/ballots/missing_ballots.html
> Fixed 270 (Missing Ballot Counter)

- mittab/apps/tab/middleware.py
- mittab/libs/backup/__init__.py
- mittab/settings.py
Fixes https://github.com/MIT-Tab/mit-tab/issues/284
Should help make backups a bit safer
> Redirect traffic to a page w/o db access during backup write/restore

- .circleci/config.yml
- Dockerfile.test
- mittab/libs/backup/strategies/local_dump.py
- nginx.conf
Makes things a bit more reliable, fixes #286 and #282
> Use mysqldump for backups

- mittab/libs/tab_logic/stats.py
As titled, dumb non-return bug
> Fix bug with bye speaks

- assets/js/pairing.js
- mittab/apps/tab/pairing_views.py
> Fix bug displaying stats in pairings

- mittab/libs/assign_judges.py
This is preventing judge assignment from working for non R4s...
> Fixing an issue with judge assignment introduced in Feb 2022

- assets/js/pairing.js
Formerly a one liner in the room dropdowns branch that didn't belong there Fixes #357
> Remove random tab card 404s. Fixed #357

- mittab/apps/tab/pairing_views.py
- mittab/templates/ballots/missing_ballots.html
> Room Number on Missing Ballots Page

- mittab/apps/tab/debater_views.py
- mittab/apps/tab/judge_views.py
- mittab/apps/tab/team_views.py
- mittab/apps/tab/views.py
- mittab/templates/common/data_entry.html
- mittab/templates/tab/debater_detail.html
- mittab/templates/tab/judge_detail.html
- mittab/templates/tab/room_detail.html
- mittab/templates/tab/school_detail.html
- mittab/templates/tab/team_detail.html
Should make searching for information much more natural. If you need to check something on all teams from a school, visit their school page. If someone left a jacket in a room, you can see everyone who debated or judged there.
> Add detail tables for related objects
