MIT-Tab/mit-tab

- Dockerfile.web
We shouldn't be running `initialize_tourney` and `migrate` from the dockerfile
> Improve dockerfile

- .env
- docker-compose.yml
- mittab/settings.py
- requirements.txt
adresses https://github.com/jolynch/mit-tab/issues/67
Depends on this PR being merged: https://github.com/BenMusch/mittab-deploy/pull/24 so that the environment variable can be set
> Integrate sentry.io for error monitoring

- mittab/apps/tab/debater_views.py
- mittab/apps/tab/judge_views.py
- mittab/apps/tab/team_views.py
- mittab/apps/tab/views.py
Deleting a team/room/debater/judge can destroy results. The "Delete" button is much clearer than the "check out" option so people may click it without thinking. Let's prevent people from making a choice with unclear (but very bad) implications
> Remove delete buttons

- mittab/apps/tab/pairing_views.py
Fixes the issue at Yale referenced here: https://github.com/jolynch/mit-tab/issues/123
Refreshing after assigning judges would re-assign judges which is bad
> Backup before judge assignments + don't return a form after assigning judges

- mittab/apps/tab/models.py
One option for addressing https://github.com/jolynch/mit-tab/issues/124
Alternatively, tab could just ignore the no-shows if there is a round.
> Delete no-shows for teams once a round is saved

- README.md
Without specifying the protocol, Github assumed the link was a subpath.
> README: Fix link to documentation

- docs/Before-Round-1.md
From ea13284691721bae3d36b162e5a25b8c67aebe53: "Discrtionary" -> "Discretionary"
> Fix typo in Docs

- mittab/apps/tab/archive.py
- mittab/apps/tab/views.py
- mittab/templates/base/_navigation.html
- mittab/templates/navigation.html
- mittab/urls.py
The Tournament Archive or DebateXML is an XML-based format for the interchange of debate tournament data. Its schema is currently under review in TabbycatDebate/dta-spec#4.
This commit adds an admin form to export the site's data through that specification for archival and analysis. The page is available through `/archive/download/`, which asks for some supplementary details, such as the tournament's name.
A link to the form should be in the navigation; however, it doesn't seem to be there.
Byes are not yet handled.
> Add ability to export as a Tournament Archive

- mittab/apps/tab/archive.py
- Team ballots must be before speeches
- Ranks must be integers
> Archive: Minor corrections to ballots

- mittab/libs/assign_judges.py
Before, the weighting system placed a high priority on placing judges in equally-matched rooms. Now, the algorithm should still prefer that, but it will always prefer a higher ranked judge. Some examples. Here is an example of a major issue which occurred with the previous algorithm:
Say 2 judges are conflicted from every room except the 10th-best room. If 1 judge is the 10th-best judge, and the other is the 1st-best judge, the weight for the 10th best judge would be `0` and for the 1st-best it would be `-9`. This seems wrong, as we would prefer the best judge be paired in.
The calculation of `-1 * abs(judge_i - (-1 * pairing_i))` solves this problem because:
* For all rounds, the highest-ranked judge will always be preferred to a lower-ranked judge
* We still preserve power-pairing …
> Change judge weights so high-ranked judges are always preferred to lower ones

- mittab/templates/pairing/pairing_control.html
This way the controls aren't blocked by error messages
> Move the error message location in pairing controls [Fixes #238]

- mittab/templates/base/_navigation.html
- mittab/urls.py
Ran into this problem at Columbia — had temporarily logged in to tab on someone's computer and there was no logout button (without going to admin)!
Edited master template, as well as disambiguated two url routes to allow url helper to function properly.
Simply a time saver.
> Logout button

- mittab/apps/tab/debater_views.py
- mittab/apps/tab/forms.py
- mittab/apps/tab/team_views.py
- mittab/apps/tab/views.py
- mittab/libs/cache_logic.py
- mittab/templates/tab/rank_debaters_component.html
- mittab/templates/tab/rank_teams.html
- mittab/templates/tab/rank_teams_component.html
- mittab/urls.py
I believe this answers #156 
Whenever the results (team or speaker) are generated, they are cached.
If a round result is changed (ie who won changed, or a speaker score / position changed) OR the force refresh button is pressed (individual to each ranking), the cache is cleared.
The makes loading the results after it has been cached pseudo-instantaneous.
> Caching results works

- mittab/settings.py
Too many people are gonna ping the server for pairings, etc. For this to be viable
Instead we should just wrap important logic in transactions
> Disable ATOMIC_REQUESTS

- docs/Tab-Policy.md
Following discussion of the first round, the next bullet point is likely intended to explain the policy all subsequent rounds rather than all previous rounds, so use "succeeding" rather than "preceding".
> Tab-Policy: fix typo regarding byes

- assets/js/pairing.js
- mittab/apps/tab/outround_pairing_views.py
- mittab/apps/tab/pairing_views.py
- mittab/templates/pairing/judge_dropdown.html
- mittab/urls.py
People keep asking for this, and the existing dropdown seemed like the easiest place to put it without interfering too much with the existing UI.
One design note:
This combines outround and inround functionality more than is ususal in the existing code base. As a result the endpoint for assign chair and remove judge for outrounds is in the pairing_views file, the outround JS is in the pairing.js file etc (mostly because the part that handles outounds is just one if statement that switches the URL or object).
Seemed preferable to repeating a lot of code, but probably goes a bit against the grain of the current design pattern, so thought it was worth flagging.
> New Judge Options: remove judge, assign chair

- mittab/libs/assign_judges.py
Noticed some super bizarre judge assignment issues this weekend. For example:
High-ranked judge A and low-ranked judge B can both judge two rounds: one high ranked and one low ranked. Yet, assign judges gives the high ranked round to the low ranked judge.
I belive this PR solves the problem. The issue is: we fetch our judges list, with related round object **before** we delete the assignments for the current round. Logging then revealed that the current judge assignment (the one before hitting assign judges again) is being counted as a rejudge.
Simply swapping the order fixes the problem
> Fix Judge Assignments

- mittab/apps/tab/team_views.py
Fix recent bug that causes tab cards with single round iron persons to not load. Bug comes from the replacement of 
`dstat2 = [k for k in RoundStats.objects.filter(debater=deb2).filter(round=round_obj).all()]`
with
`dstat2 = round_stats_by_round_and_debater_id[round_number][deb2.id]`
Which fixed the N+1, but isn't null safe. `if iron_person` doesn't fix the problem because teams that iron personed some but not all rounds have `iron_person=False`. Replacement should fix the problem, and be a little simpler.
> Tab Card Patch

- .circleci/config.yml
Ugly short term fix to getting lint and built tests passing again with the EOL images. Eventually can be removed if we get back to a LTS python version
> try to fix failing circle-ci tests

- mittab/apps/tab/team_views.py
Could have sworn I already fixed this, but getting reports it was broken again and was able to replicate it. Simple fix, we can't assume round stats are populated before results are in
> fix inround tab cards

- mittab/apps/tab/forms.py
- mittab/apps/tab/middleware.py
- settings.yaml
Reversing course on this for a few reasons:
1. In the final design on the API import we used over on standings, we ended up just letting URL be a text input rather than having a dashboard for active tournaments, so the original purpose of telling standings which tournaments to include on the dashboard isn't really relevant anymore
2. When you do spreadsheet import, if you forgot to turn the setting on, the IDs won't import and you have to try again. This is a result of removing IDs from the forms, because the spreadsheet import creates the objects using the forms for validation. Plenty of other ways to fix this, but since the original purpose is moot, it wouldn't be worth the added complexity
> Remove setting for apda_id

- assets/js/scroller.js
- mittab/templates/outrounds/pretty_pairing.html
- mittab/templates/pairing/pairing_display.html
Fixing two super nit-picky bugs
1. Auto-scroll is on by default. Since it's only used on a projector and is a bit of a nuance to people looking on a personal device, it would be a bit better to disable
2. when you turn on turn off auto-scroll, then turn it back on, it doesn't re-enable
> Disable autoscroll default
